CREATE DATABASE MOVIE;
USE MOVIE;
GO
CREATE TABLE INFO(
	id NVARCHAR(3) NOT NULL PRIMARY KEY,
	Mname NTEXT,
	Origin NTEXT,
	Price INTEGER,
)
GO
CREATE TABLE THEATERS(
	id NVARCHAR(3) NOT NULL CONSTRAINT fk_theaters_info FOREIGN KEY REFERENCES INFO(id),
	idtheater INT,
	CONSTRAINT pk_theaters PRIMARY KEY (id,idtheater)
)
GO
INSERT INTO INFO
VALUES('000', N'Đào, Phở và Piano', N'Dao, Pho and Piano', 45)
GO
INSERT INTO THEATERS
VALUES('000', 1)
GO
INSERT INTO THEATERS
VALUES('000', 2)
GO
INSERT INTO THEATERS
VALUES('000', 3)
GO


