USE [D:\PROJECTS\C#\LAB3\LAB3\THEATER\RESOURCES\DATA.MDF];
GO
INSERT INTO INFO
VALUES(N'Đào, Phở và Piano', N'Dao, Pho and Piano', 45)
GO
INSERT INTO INFO
VALUES(N'Mai', N'Mai', 100)
GO
INSERT INTO INFO
VALUES(N'Gặp Lại Chị Bầu', N'Meet My Pregnant Sister Again', 70)
GO

INSERT INTO SEAT
VALUES(1, N'Rạp 1', 2, 5, 1)
GO
INSERT INTO SEAT
VALUES(2, N'Rạp 2', 5, 3, 1)
GO
INSERT INTO SEAT
VALUES(3, N'Rạp 3', 1, 3, 1)
GO
INSERT INTO SEAT
VALUES(4, N'Rạp 4', 1, 2, 0)
GO
INSERT INTO SEAT
VALUES(5, N'Rạp 5', 0, 6, 1)
GO
INSERT INTO SEAT
VALUES(6, N'Rạp 6', 0, 0, 5)
GO
INSERT INTO SEAT
VALUES(7, N'Rạp 7', 6, 3, 2)
GO
INSERT INTO SEAT
VALUES(8, N'Rạp 8', 2, 7, 0)
GO
INSERT INTO SEAT
VALUES(9, N'Rạp 9', 0, 7, 0)
GO

INSERT INTO THEATERS
VALUES(1, 1)
GO
INSERT INTO THEATERS
VALUES(1, 2)
GO
INSERT INTO THEATERS
VALUES(1, 3)
GO
INSERT INTO THEATERS
VALUES(2, 2)
GO
INSERT INTO THEATERS
VALUES(2, 3)
GO
INSERT INTO THEATERS
VALUES(3, 1)
GO


INSERT INTO USERS
VALUES('Admin', 'admin', 1)
GO
INSERT INTO USERS
VALUES('Staff', 'user123', 2)
GO
