USE [D:\PROJECTS\C#\LAB3\LAB3\THEATER\RESOURCES\DATA.MDF];
GO

SET DATEFORMAT dmy;
GO

CREATE TABLE CLIENTS(
	Id INT PRIMARY KEY,
	IsLock BIT NOT NULL DEFAULT 1
);
GO

CREATE TABLE INFO(
	Id INT IDENTITY(1,1) NOT NULL PRIMARY KEY,
	Mname NTEXT,
	Origin NTEXT,
	Price INTEGER,
)
GO
CREATE TABLE THEATERS(
	Id INT NOT NULL,
	Idtheater INT,
	CONSTRAINT pk_theaters PRIMARY KEY (Id,Idtheater)
)
GO
CREATE TABLE SEAT(
	Id INT NOT NULL PRIMARY KEY,
	TName NTEXT,
	Normal INT,
	Vip INT,
	Sweet INT
)
GO
CREATE TABLE TICKER(
	Id INT IDENTITY(1,1) PRIMARY KEY,
	Idtheater INT,
	Idmovie INT,
	Price INT,
    Datet DATE
)
GO
CREATE TABLE BUYED(
	Id INT,
	Idseat NVARCHAR(3)
)
GO
CREATE TABLE USERS(
	Username VARCHAR(20) PRIMARY KEY,
	Pass VARCHAR(20) NOT NULL,
	Permit INT
)
GO
ALTER TABLE THEATERS ADD CONSTRAINT fk_theaters_info FOREIGN KEY (Id) REFERENCES INFO(Id);
GO
ALTER TABLE THEATERS ADD CONSTRAINT fk_theaters_seat FOREIGN KEY (Idtheater) REFERENCES SEAT(Id);
GO
ALTER TABLE TICKER ADD CONSTRAINT fk_ticker_info FOREIGN KEY (Idmovie) REFERENCES INFO(Id);
GO
ALTER TABLE TICKER ADD CONSTRAINT fk_ticker_seat FOREIGN KEY (Idtheater) REFERENCES SEAT(Id);
GO
ALTER TABLE BUYED ADD CONSTRAINT fk_buyed_ticker FOREIGN KEY (Id) REFERENCES TICKER(Id);
GO
--DROP TABLE INFO;
--DROP TABLE THEATERS;
--DROP TABLE USERS;
--DROP TABLE BUYED;